#! /usr/bin/env python3


import socket
from args import argsParser
import threading

HOST = '172.27.5.188'
PORT = 4444


work = [x for x in range(1,100)]
totalWork = len(work)
args = argsParser()

def main():
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        s.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
        s.bind((HOST,PORT))
        print('[+] listening connection on ' + HOST)
        while True:
            s.listen()
            conn, addr = s.accept()
            print(f'[+] node connected with ip: {addr}')
            threading.Thread(target=workToDo, args=(conn,addr,)).start()

def workToDo(conn, addr):
    print('start thread')
    with conn:
        with open('pass.lst') as file:
            conn.send(file.read().encode())
        while True:
            try:
                currentWork = work.pop()
                command = f'{args.command} --node:{currentWork}/{totalWork}'
                conn.sendall(command.encode())
                data = conn.recv(1024).decode()
                print(data)
                print(f' {addr} end work: {currentWork}')
            except Exception as e:
                print(e)
                break


if __name__ == "__main__":
    main()
