#! /usr/bin/env python3

# nodes
import socket
import subprocess
from time import sleep

HOST = '172.27.5.188'
PORT = 4444

with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
    while True:
        try:
            s.connect((HOST, PORT))
            with open('test.lst','w') as file:
                file.write(s.recv(1024).decode())
            break
        except:
            print('wait server...')
            sleep(2)
            pass

    while True:
        try:
            #sleep(2)
            data = s.recv(1024)

            print(data.decode())
            if data:
                data = data.decode() + ' test.lst'
                print('start working')
                output = subprocess.check_output(data,shell=True)
                s.send(output)
                print('end working')
            if not data:
                break
        except Exception as error:
            print(error)
            break
